/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.praktikum9;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class LihatDataPanel extends javax.swing.JPanel {

    /**
     * Creates new form LihatDataPanel
     */
    public LihatDataPanel() {
        initComponents();
        loadData();
    }
    private void loadData(){
        String [] colomn = {"nama", "NIM", "Prodi", "Jenis Kelamin", "Status"};
        DefaultTableModel table = new DefaultTableModel (null, colomn){
            @Override
            public boolean isCellEditable (int row, int coloumn){
                return false;
            }
        };
        
        for (Mahasiswa mhs: Mahasiswa.mahasiswas){
            table.addRow (new String[]{
                mhs.getNama(), mhs.getNIM(), mhs.getProdi(), mhs.getJenisKelamin(), mhs.isActive()? "Aktif" : "Tidak Aktif"
            });
        }
        mahasiswaTable.setModel(table);
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        mahasiswaTable = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(530, 400));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(530, 300));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Lihat Data Mahasiswa");

        mahasiswaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        mahasiswaTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mahasiswaTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(mahasiswaTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        add(jPanel1, "card2");
    }// </editor-fold>                        

    private void mahasiswaTableMouseClicked(java.awt.event.MouseEvent evt) {                                            
       int row = mahasiswaTable.getSelectedRow();
        if (row >= 0) {
            String nama = mahasiswaTable.getValueAt(row, 0).toString();
            String nim = mahasiswaTable.getValueAt(row, 1).toString();
            String prodi = mahasiswaTable.getValueAt(row, 2).toString();
            String jk = mahasiswaTable.getValueAt(row, 3).toString();
            String status = mahasiswaTable.getValueAt(row, 4).toString();

            Object[] options = {"Edit", "Hapus", "Batal"};
            int pilihan = JOptionPane.showOptionDialog(
                    this,
                    "pilih",
                    "edit dl",
                    JOptionPane.DEFAULT_OPTION,
                    JOptionPane.INFORMATION_MESSAGE,
                    null,
                    options,
                    options[0]);

            switch (pilihan) {
                case 0:

                    JOptionPane.showMessageDialog(this,
                            "Nama: " + nama + "NIM: " + nim  + "Prodi: " + prodi  + "Jenis Kelamin: " + jk  + "Status: " + status,"Detail Mahasiswa",JOptionPane.INFORMATION_MESSAGE);
                break;
                    
                case 1:
                    String newNama = JOptionPane.showInputDialog(this, "Ubah Nama:", nama);
                    if (newNama != null && !newNama.isBlank()) {
                        Mahasiswa.mahasiswas.get(row).setNama(newNama);
                    }
                    
                    String newNim = JOptionPane.showInputDialog(this, "Ubah NIM:", nim);
                    if (newNim != null && !newNim.isBlank()) {
                        Mahasiswa.mahasiswas.get(row).setNama(newNama);
                    }

                    String newProdi = JOptionPane.showInputDialog(this, "Ubah Prodi:", prodi);
                    if (newProdi != null && !newProdi.isBlank()) {
                        Mahasiswa.mahasiswas.get(row).setProdi(newProdi);
                    }
                    
                    String newJk = JOptionPane.showInputDialog(this, "Ubah Jenis Kelamin:", jk);
                    if (newJk != null && !newJk.isBlank()) {
                        Mahasiswa.mahasiswas.get(row).setProdi(newProdi);
                    }

                    String newStatus = JOptionPane.showInputDialog(this, "Ubah Status (Aktif/Tidak Aktif):", status);
                    if (newStatus != null) {
                        Mahasiswa.mahasiswas.get(row).setActive(newStatus.equalsIgnoreCase("Aktif"));
                    }

                    loadData();
                    JOptionPane.showMessageDialog(this, "Data berhasil diubah!");
                    break;

                case 2:

                    int konfirmasi = JOptionPane.showConfirmDialog(this,
                            "Yakin ingin menghapus data " + nama + "?",
                            "Konfirmasi Hapus",
                            JOptionPane.YES_NO_OPTION);

                    if (konfirmasi == JOptionPane.YES_OPTION) {
                        Mahasiswa.mahasiswas.remove(row);
                        loadData();
                        JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
                    }
                    break;

                default:
                    break;
            }
        }
    }                                           


    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable mahasiswaTable;
    // End of variables declaration                   
}
