/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.praktikum9;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class TambahDataPanel extends javax.swing.JPanel {

    /**
     * Creates new form TambahDataPanel
     */
    public TambahDataPanel() {
        initComponents();
    }
    private void clearform (){
        inputNama.setText("");
        inputNIM.setText("");
        rdLakiLaki.setSelected(false);
        rdPerempuan.setSelected(false);
        checkBoxStatus.setSelected(false);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jkbtn = new javax.swing.ButtonGroup();
        JPanel1 = new javax.swing.JPanel();
        tambahDataMahasiswa = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        NIM = new javax.swing.JLabel();
        prodi = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        inputNIM = new javax.swing.JTextField();
        inputNama = new javax.swing.JTextField();
        comboBoxProdi = new javax.swing.JComboBox<>();
        rdPerempuan = new javax.swing.JRadioButton();
        rdLakiLaki = new javax.swing.JRadioButton();
        checkBoxStatus = new javax.swing.JCheckBox();
        btnKirim = new javax.swing.JButton();
        namaAlert = new javax.swing.JLabel();
        nimAlert = new javax.swing.JLabel();
        prodiAlert = new javax.swing.JLabel();
        jkAlert = new javax.swing.JLabel();
        statusAlert = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));
        setPreferredSize(new java.awt.Dimension(530, 400));
        setLayout(new java.awt.CardLayout());

        JPanel1.setBackground(new java.awt.Color(255, 204, 204));
        JPanel1.setPreferredSize(new java.awt.Dimension(530, 400));

        tambahDataMahasiswa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tambahDataMahasiswa.setText("Tambah Data Mahasiswa");

        nama.setText("Nama");

        NIM.setText("NIM");

        prodi.setText("Prodi");

        jLabel5.setText("Jenis Kelamin");

        jLabel6.setText("Status");

        inputNIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNIMActionPerformed(evt);
            }
        });

        inputNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNamaActionPerformed(evt);
            }
        });

        comboBoxProdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S1 Teknik Informatika", "S1 Teknik Elektro", "D3 Teknik Elektro" }));
        comboBoxProdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxProdiActionPerformed(evt);
            }
        });

        rdPerempuan.setBackground(new java.awt.Color(255, 204, 204));
        jkbtn.add(rdPerempuan);
        rdPerempuan.setText("Perempuan");
        rdPerempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdPerempuanActionPerformed(evt);
            }
        });

        rdLakiLaki.setBackground(new java.awt.Color(255, 204, 204));
        jkbtn.add(rdLakiLaki);
        rdLakiLaki.setText("Laki-Laki");
        rdLakiLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdLakiLakiActionPerformed(evt);
            }
        });

        checkBoxStatus.setBackground(new java.awt.Color(255, 204, 204));
        checkBoxStatus.setText("Aktif");
        checkBoxStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxStatusActionPerformed(evt);
            }
        });

        btnKirim.setBackground(new java.awt.Color(204, 255, 255));
        btnKirim.setText("Kirim");
        btnKirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKirimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanel1Layout = new javax.swing.GroupLayout(JPanel1);
        JPanel1.setLayout(JPanel1Layout);
        JPanel1Layout.setHorizontalGroup(
            JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel1Layout.createSequentialGroup()
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(170, 170, 170)
                                .addComponent(btnKirim))
                            .addComponent(tambahDataMahasiswa)
                            .addGroup(JPanel1Layout.createSequentialGroup()
                                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JPanel1Layout.createSequentialGroup()
                                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(prodi)
                                            .addComponent(jLabel5))
                                        .addGap(30, 30, 30))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel1Layout.createSequentialGroup()
                                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(NIM, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(inputNama, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                                    .addComponent(inputNIM, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                                    .addComponent(comboBoxProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(JPanel1Layout.createSequentialGroup()
                                        .addComponent(rdPerempuan)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdLakiLaki, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(namaAlert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nimAlert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(prodiAlert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jkAlert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(JPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkBoxStatus)
                            .addComponent(statusAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 52, Short.MAX_VALUE))
        );
        JPanel1Layout.setVerticalGroup(
            JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(tambahDataMahasiswa)
                .addGap(18, 18, 18)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nama)
                    .addComponent(inputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaAlert)
                .addGap(4, 4, 4)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NIM)
                    .addComponent(inputNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nimAlert)
                .addGap(5, 5, 5)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prodi)
                    .addComponent(comboBoxProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodiAlert)
                .addGap(13, 13, 13)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rdPerempuan)
                    .addComponent(rdLakiLaki))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jkAlert)
                .addGap(8, 8, 8)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(checkBoxStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusAlert)
                .addGap(7, 7, 7)
                .addComponent(btnKirim)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(JPanel1, "card2");
    }// </editor-fold>                        

    private void inputNIMActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void rdPerempuanActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void checkBoxStatusActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void btnKirimActionPerformed(java.awt.event.ActionEvent evt) {                                         
       String nama = inputNama.getText();
       String NIM = inputNIM.getText();
       String prodi = (String)comboBoxProdi.getSelectedItem();
       String jenisKelamin = rdPerempuan.isSelected()?"perempuan":"Laki-Laki";
       boolean isActive = checkBoxStatus.isSelected();
       
        boolean error = false;
        boolean cekNim = false;
       for (Mahasiswa m : Mahasiswa.mahasiswas) {
        if (m.getNIM().equals(NIM)) {
        cekNim = true;
        break;
    }
}

    namaAlert.setText("");
    nimAlert.setText("");
    prodiAlert.setText("");
    jkAlert.setText("");
    statusAlert.setText("");


if (nama.isEmpty()) {
    namaAlert.setText("Nama tidak boleh kosong!");
    namaAlert.setForeground(Color.red);
    error = true;
} else if (!nama.matches("[a-zA-Z\\s]+")) {
    namaAlert.setText("Nama hanya boleh berisi huruf!");
    namaAlert.setForeground(Color.red);
    error = true;
}


else if (NIM.isEmpty()) {
    nimAlert.setText("NIM tidak boleh kosong!");
    nimAlert.setForeground(Color.red);
    error = true;
} else if (!NIM.matches("\\d+")) {
    nimAlert.setText("NIM harus berupa angka!");
    nimAlert.setForeground(Color.red);
    error = true;
} else if (cekNim) {
    nimAlert.setText("NIM sudah terdaftar!");
    nimAlert.setForeground(Color.red);
    error = true;
}


else if (prodi == null) {
    prodiAlert.setText("Prodi harus dipilih!");
    prodiAlert.setForeground(Color.red);
    error = true;
}


else if (jkbtn.getSelection() == null) {
    jkAlert.setText("Pilih jenis kelamin!");
    jkAlert.setForeground(Color.red);
    error = true;
}


else if (!checkBoxStatus.isSelected()) {
    statusAlert.setText("Status harus dipilih!");
    statusAlert.setForeground(Color.red);
    error = true;
}

// Jika ada error, hentikan proses
if (error) {
    return;
}

       
       Mahasiswa mahasiswa = new Mahasiswa (nama,NIM,prodi,jenisKelamin,isActive);
       Mahasiswa.mahasiswas.add(mahasiswa);
       
       JOptionPane.showMessageDialog(this,"sukses menambahkan data mahasiswa "+ nama);
       clearForm();
       
    }                                        

    private void inputNamaActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void rdLakiLakiActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void comboBoxProdiActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             


    // Variables declaration - do not modify                     
    private javax.swing.JPanel JPanel1;
    private javax.swing.JLabel NIM;
    private javax.swing.JButton btnKirim;
    private javax.swing.JCheckBox checkBoxStatus;
    private javax.swing.JComboBox<String> comboBoxProdi;
    private javax.swing.JTextField inputNIM;
    private javax.swing.JTextField inputNama;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jkAlert;
    private javax.swing.ButtonGroup jkbtn;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel namaAlert;
    private javax.swing.JLabel nimAlert;
    private javax.swing.JLabel prodi;
    private javax.swing.JLabel prodiAlert;
    private javax.swing.JRadioButton rdLakiLaki;
    private javax.swing.JRadioButton rdPerempuan;
    private javax.swing.JLabel statusAlert;
    private javax.swing.JLabel tambahDataMahasiswa;
    // End of variables declaration                   

    private void clearForm() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
