
package com.mycompany.praktikum_2.TugasPrak2;

/**
 *
 * @author Faridz Talbi
 */
public class TugasPrak2 {
    public static void main (String[] args){
    
    String nama = " Raja Muhammad Faridz Talbi ";
    String NIM = "2407111265";
    String Alamat = " Jalan Garuda Sakti";
    int umur;
        umur = 19;
        
    final String GolonganDarah = " AB+ ";   
    
    double[] IpSemester = {3.3, 3.4, 3.8, 3.9};
    byte byteSemester = (byte)IpSemester[2];
    
    System.out.println(" Nama Saya " + nama);
    System.out.println(" NIM Saya " + NIM);
    System.out.println(" Umur Saya " + umur);
    System.out.println(" Golongan darah Saya " + GolonganDarah);
    System.out.println(" Alamat Saya" + Alamat);
    System.out.println(" Nilai  IP semester 3 saya " + IpSemester[3]);
    System.out.println(" Nilai  IP semester 3 saya setelah jika dikonversi ke byte = " + byteSemester);
   
       
        
    }
}
