/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.smartcontrol;

import java.awt.Color;

/**
 *
 * @author lenov
 */
public class SettingsPanel extends javax.swing.JPanel {
    private MainFrame mainFrame;

    /**
     * Creates new form SettingsPanel
     */
    public SettingsPanel(MainFrame frameUtama) {
        this.mainFrame = frameUtama;
        initComponents();
       usnField.setText(MainFrame.username);
        
        if (topikField != null) {
            topikField.setText(MainFrame.topik);
        }
  
        if (jedaSpinner != null) {
            jedaSpinner.setValue(MainFrame.waktuKuis);
        }
        
        if (hukumanSpinner != null) {
            hukumanSpinner.setValue(MainFrame.waktuHukuman);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        usnLbl = new javax.swing.JLabel();
        passLbl = new javax.swing.JLabel();
        usnField = new javax.swing.JTextField();
        passField = new javax.swing.JTextField();
        akunAlert = new javax.swing.JLabel();
        tambahLbl = new javax.swing.JPanel();
        jedaLbl = new javax.swing.JLabel();
        hukumanLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jedaSpinner = new javax.swing.JSpinner();
        hukumanSpinner = new javax.swing.JSpinner();
        topikField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        logoutBtn = new javax.swing.JButton();
        quizBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();

        jPasswordField1.setText("jPasswordField1");

        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(0, 0));
        setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(94, 190, 242));
        jPanel3.setLayout(new java.awt.GridLayout(0, 1));

        jPanel2.setBackground(new java.awt.Color(94, 190, 242));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pengaturan Akun"));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        usnLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        usnLbl.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(usnLbl, gridBagConstraints);

        passLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        passLbl.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel2.add(passLbl, gridBagConstraints);

        usnField.setPreferredSize(new java.awt.Dimension(250, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel2.add(usnField, gridBagConstraints);

        passField.setPreferredSize(new java.awt.Dimension(250, 35));
        passField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanel2.add(passField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel2.add(akunAlert, gridBagConstraints);

        jPanel3.add(jPanel2);

        tambahLbl.setBackground(new java.awt.Color(94, 190, 242));
        tambahLbl.setBorder(javax.swing.BorderFactory.createTitledBorder("Pengaturan Aplikasi"));
        tambahLbl.setLayout(new java.awt.GridBagLayout());

        jedaLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jedaLbl.setText("Jeda Waktu ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        tambahLbl.add(jedaLbl, gridBagConstraints);

        hukumanLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hukumanLbl.setText("Waktu Hukuman");
        hukumanLbl.setRequestFocusEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        tambahLbl.add(hukumanLbl, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Tambah Topik");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        tambahLbl.add(jLabel1, gridBagConstraints);

        jedaSpinner.setPreferredSize(new java.awt.Dimension(250, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        tambahLbl.add(jedaSpinner, gridBagConstraints);

        hukumanSpinner.setPreferredSize(new java.awt.Dimension(250, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        tambahLbl.add(hukumanSpinner, gridBagConstraints);

        topikField.setPreferredSize(new java.awt.Dimension(250, 35));
        topikField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topikFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        tambahLbl.add(topikField, gridBagConstraints);

        jPanel3.add(tambahLbl);

        add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(94, 190, 242));

        logoutBtn.setText("Logout");
        logoutBtn.setPreferredSize(new java.awt.Dimension(90, 35));
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        jPanel1.add(logoutBtn);

        quizBtn.setText("Quiz");
        quizBtn.setPreferredSize(new java.awt.Dimension(90, 35));
        quizBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quizBtnActionPerformed(evt);
            }
        });
        jPanel1.add(quizBtn);

        saveBtn.setText("Save");
        saveBtn.setPreferredSize(new java.awt.Dimension(90, 35));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        jPanel1.add(saveBtn);

        add(jPanel1, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void passFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passFieldActionPerformed

    private void quizBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quizBtnActionPerformed
        // TODO add your handling code here:
        mainFrame.gantiPanel("quiz_panel");
    }//GEN-LAST:event_quizBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        mainFrame.gantiPanel("login_panel");
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void topikFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topikFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_topikFieldActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        String u = usnField.getText().trim();
        String p = passField.getText().trim();
        String t = topikField.getText().trim();
        int wKuis = (Integer) jedaSpinner.getValue();
        int wHukum = (Integer) hukumanSpinner.getValue();

    if (u.isEmpty() || p.isEmpty() || t.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Username, Password, dan Topik tidak boleh kosong!", 
            "Gagal Simpan", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (wKuis <= 0 || wHukum <= 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Waktu harus lebih dari 0!");
        return;
    }

    // 4. SIMPAN SEMUANYA
    mainFrame.simpanData(u, p, t, wKuis, wHukum);

    javax.swing.JOptionPane.showMessageDialog(this, "Pengaturan Berhasil Disimpan!");
    }//GEN-LAST:event_saveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel akunAlert;
    private javax.swing.JLabel hukumanLbl;
    private javax.swing.JSpinner hukumanSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel jedaLbl;
    private javax.swing.JSpinner jedaSpinner;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JTextField passField;
    private javax.swing.JLabel passLbl;
    private javax.swing.JButton quizBtn;
    private javax.swing.JButton saveBtn;
    private javax.swing.JPanel tambahLbl;
    private javax.swing.JTextField topikField;
    private javax.swing.JTextField usnField;
    private javax.swing.JLabel usnLbl;
    // End of variables declaration//GEN-END:variables
}
